# Задания по библиотеке `NumPy`

Дан массив, содержащий баллы слушателей курса по английскому языку за вступительный экзамен. Слушатели распределены по 15 группам по 10 человек.

In [1]:
import numpy as np
scores = np.array([[20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
         [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
         [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
         [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
         [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
         [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
         [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
         [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
         [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
         [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
         [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
         [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
         [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
         [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
         [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])



### Задание 1

Посчитать, сколько слушателей получили 0 за вступительный экзамен.
import numpy as np
scores = np.array([[20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
         [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
         [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
         [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
         [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
         [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
         [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
         [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
         [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
         [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
         [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
         [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
         [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
         [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
         [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])
count_of_zeros = np.count_nonzero(scores == 0)

print("Количество нулей в массиве:", count_of_zeros)

In [2]:
import numpy as np
scores = np.array([[20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
         [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
         [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
         [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
         [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
         [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
         [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
         [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
         [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
         [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
         [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
         [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
         [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
         [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
         [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])
count_of_zeros = np.count_nonzero(scores == 0)

print("Количество нулей в массиве:", count_of_zeros)

Количество нулей в массиве: 13


### Задание 2

Посчитать, сколько слушателей получили балл выше 50.

In [3]:


task2 = np.count_nonzero(scores > 50)

print(task2)

64


### Задание 3

Посчитать, сколько человек получили балл не ниже 50, но не выше 70.

In [4]:
task3 = np.count_nonzero((scores >= 50) & (scores <= 70))
print(task3)

26


### Задание 4

Определить, в какой группе средний балл за вступительный экзамен выше.

In [5]:
mean_scores = np.mean(scores, axis=1)
task4 = np.argmax(mean_scores)
#print(mean_scores)
print(task4)

9


### Задание 5

Сохранить баллы слушателей выше 0 в массив `nonzero`. Укажите кол-во элементов получившегося массива.

In [6]:
### YOUR CODE HERE ###
nonzero = scores[scores > 0]
count_nonzero = nonzero.size
print("Массив с баллами выше 0:", nonzero)
print("Количество элементов в массиве nonzero:", count_nonzero)

Массив с баллами выше 0: [ 20  40  56  80   5  25  27  74   1  98  67 100   8  56  34  82 100   7
  78  54  23  79 100  42  95  83  51  50  47  23 100  94  25  48  38  77
  90  87  41  89  52   5  17  28  99  32  18  21  18  29  31  48  62  76
  22   6  65  78  43  22  38  88  94 100  77  28  39  41  81  45  54  98
  12  66  88  44  55 100  12  11  17  70  86  96  56  23  32  49  70  80
  20  24  76  50  29  40   3   2   5  11  33  63  28  40  51 100  98  87
  22  30  16  54  78  12  25  35  10  19  67 100  88  24  33  47  56  62
  34  77  53  50  89  70  72  56  29  15  20]
Количество элементов в массиве nonzero: 137


### Задание 6

Используя массив `nonzero`, определить минимальный балл за вступительный балл по всем группам.

In [7]:
### YOUR CODE HERE ###
nonzero = scores[scores > 0]
min_score = np.min(nonzero)
print(min_score)


1


### Задание 7

Выбрать из массива `nonzero` только те значения, которые соответствуют продвинутому уровню знания языка – баллу за экзамен выше 80. Сохранить полученный результат в массив `advanced`. В заданиях 8-10 нужно работать с массивом `advanced`.

In [8]:
### YOUR CODE HERE ###
advanced = nonzero[nonzero > 80]

print(advanced)

[ 98 100  82 100 100  95  83 100  94  90  87  89  99  88  94 100  81  98
  88 100  86  96 100  98  87 100  88  89]


### Задание 8

Определить размерность массива `advanced`.

In [9]:
### YOUR CODE HERE ###
task8 = advanced.ndim 
print(task8)

1


### Задание 9

Определить форму массива `advanced`.

In [10]:
### YOUR CODE HERE ###
task9=advanced.shape
print(task9)

(28,)


### Задание 10

Определить общее число элементов в массиве `advanced`.

In [11]:
### YOUR CODE HERE ###
task10 = advanced.size
print(task10)

28


### Задание 11

На основе исходного массива `scores` создать булев массив `sto`, где `True` соответствует баллам за экзамен, равным 100, а `False` – всем остальным баллам. 

In [12]:
### YOUR CODE HERE ###
sto = (scores == 100)
print(sto)

[[False False False False False False False False False False]
 [False False False  True False False False False  True False]
 [False False False False  True False False False False False]
 [False False False False  True False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False  True]
 [False False False False False False False False False False]
 [False False False False False False False  True False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False  True False False False False]
 [False False False False False False False False False False]
 [ True False False False False False False False False False]
 [False False False False False False False False False False]]


### Задание 12

На основе исходного массива `scores` вывести на экран оценки слушателей первых семи групп (включительно, должны быть 7 списков оценок).

In [13]:
### YOUR CODE HERE ###
for i in range(7):
    print(f"{i}: {scores[i]}")

0: [20 40 56 80  0  5 25 27 74  1]
1: [  0  98  67 100   8  56  34  82 100   7]
2: [ 78  54  23  79 100   0   0  42  95  83]
3: [ 51  50  47  23 100  94  25  48  38  77]
4: [90 87 41 89 52  0  5 17 28 99]
5: [32 18 21 18 29 31 48 62 76 22]
6: [  6   0  65  78  43  22  38  88  94 100]


### Задание 13

Студент N подрабатывает репетитором по математике и ведёт занятия разных типов: готовит к ЕГЭ, к олимпиадам, «подтягивает» математику у школьников младших классов. 

В массиве `classes` хранится число проведённых уроков за пять рабочих дней, в массиве `prices` — стоимость одного урока (считаем, что студент за день проводит занятия одного типа, одинаковые по стоимости).

Определить доход студента за неделю, используя [метод](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) `.dot()` для нахождения [скалярного произведения](https://ru.wikipedia.org/wiki/%D0%A1%D0%BA%D0%B0%D0%BB%D1%8F%D1%80%D0%BD%D0%BE%D0%B5_%D0%BF%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5). 

In [14]:
classes = np.array([3, 3, 2, 0, 2])
prices = np.array([1500, 1500, 2500, 1000, 1000])

In [15]:
### YOUR CODE HERE ###
print(np.dot(classes,prices))

16000


### Задание 14

По результатам работы с данными по оценкам за эссе студентов, поставленным двумя разными экспертами, были созданы два булевых массива `expert1` и `expert2`, в которых значение `True` означает оценку «удовлетворительно» и выше, а значение `False` – неудовлетворительно. Всего было оценено 15 эссе, по 5 эссе на каждую из трёх тем.

In [16]:
expert1 = np.array([[True, False, False, True, True],
                   [False, True, False, False, True],
                   [True, True, True, False, False]])
expert2 = np.array([[True, False, False, False, True],
                   [False, False, False, False, False],
                   [True, False, True, False, False]])

Определить, используя различные логические операторы (`|`, `&`, и проч.) и вспомогательные методы/функции, сколько студентов получат зачёт, если известно, что для этого необходимо получить оценку не ниже удовлетворительной у обоих экспертов.

In [17]:
### YOUR CODE HERE ###
passing_students = expert1 & expert2
number_of_passed_students = passing_students.sum()
print(f"Количество студентов, получивших зачет: {number_of_passed_students}")

Количество студентов, получивших зачет: 4


Были получены данные об оценках третьего эксперта. Определите, сколько студентов получат зачёт, если известно, что для этого необходимо получить оценку не ниже удовлетворительной хотя бы у двух экспертов. При решении используйте только логические операторы.

In [18]:
expert3 = np.array([[True, False, True, False, True],
                   [False, True, False, False, False],
                   [False, True, True, False, True]])

In [19]:
### YOUR CODE HERE ###
passing_students_2 = expert1 & expert2 | expert2 & expert3 | expert3 & expert1
number_of_passed_students_2=passing_students_2.sum()
print(number_of_passed_students_2)


6


### Задание 15

Дан массив `essay` с итоговыми оценками студентов за эссе из задачи 14 **с двумя экспертами**:

In [20]:
# pass - сдал
# not pass - не сдал

essay = np.array([["pass", "not pass", "not pass", "not pass", "pass"],
        ["not pass", "not pass", "not pass", "not pass", "not pass"],
        ["pass", "not pass", "pass", "not pass", "not pass"]])

Проверить ответ в предыдущей задаче, используя массив `essay`. Решение должно быть представлено в виде кода, не в виде выводов в результате явного подсчёта элементов.

In [21]:
### YOUR CODE HERE ###
print(passing_students)
print(essay)

passing_students_binary = passing_students.astype(int)

# Преобразование строкового массива в массив нулей и единиц
essay_binary = np.where(essay == 'pass', 1, 0)

# Сравнение массивов
are_equal = np.array_equal(passing_students_binary, essay_binary)

if are_equal:
    print("Массивы совпадают.")
else:
    print("Массивы не совпадают.")
    


[[ True False False False  True]
 [False False False False False]
 [ True False  True False False]]
[['pass' 'not pass' 'not pass' 'not pass' 'pass']
 ['not pass' 'not pass' 'not pass' 'not pass' 'not pass']
 ['pass' 'not pass' 'pass' 'not pass' 'not pass']]
Массивы совпадают.


### Задание 16

Используя массивы `expert1` и `expert2` из задачи 14, определить согласованность двух экспертов, используя меру близости Жаккара, которая вычисляется следующим образом:

$$
J(A, B) = \frac{|A \cap B|}{|A| + |B| - |A \cap B|}
,$$ 

где $A$ – первое множество, $B$ – второе множество, $A \cap B$ – пересечение множеств, т.е. их общие элементы. Запись $|A|$ означает «количество элементов в множестве». 

В качестве множеств $A$ и $B$ в данной задаче выступают множества (группы) студентов, которые получили зачёт у первого и второго экспертов.

In [22]:
### YOUR CODE HERE ###

import numpy as np

expert1 = np.array([[True, False, False, True, True],
                   [False, True, False, False, True],
                   [True, True, True, False, False]])
expert2 = np.array([[True, False, False, False, True],
                   [False, False, False, False, False],
                   [True, False, True, False, False]])

def jaccard_index(expert1, expert2):
    # Преобразуем логические массивы в множества индексов студентов с зачетом
    set1 = {i for i in range(expert1.shape[0]) for j in range(expert1.shape[1]) if expert1[i][j]}
    set2 = {i for i in range(expert2.shape[0]) for j in range(expert2.shape[1]) if expert2[i][j]}

    # Находим пересечение и объединение множеств
    intersection = len(set1.intersection(set2))
    union = len(set1) + len(set2) - intersection
    
    # Вычисляем коэффициент Жаккара
    if union == 0:  # Избегаем деления на ноль
        return 0.0
    return intersection / union

# Вычисляем коэффициент Жаккара для обоих экспертов
jaccard_result = jaccard_index(expert1, expert2)

# Выводим результат
print("Коэффициент Жаккара:", jaccard_result)

Коэффициент Жаккара: 0.6666666666666666


### Задание 17
Загрузить из файла `array_hw.npy` массив и сохранить его как `arr`. Массив содержит объёмы продаж мороженого (в штуках) в 5 магазинах за одну неделю в июне (7 дней, с понедельника до воскресенья). В заданиях 18-20 нужно работать с массивом `arr`.

In [23]:
### YOUR CODE HERE ###
arr = np.load('array_hw.npy')

# Выводим загруженный массив для проверки
print(arr)

[[100  80  70  60 120]
 [ 65  55  20  50  60]
 [ 80  90  75  80  60]
 [ 45  60  70  20  40]
 [ 82  47  56  89  92]
 [115 120 113 106 107]
 [ 46  74  23  34  19]]


### Задание 18
Если думать о массиве `arr` как о таблице, сейчас в таблице магазины идут по столбцам (1 магазин = 1 столбец, всего 5), а дни – по строкам (1 день = 1 строка, всего 7). Преобразовать массив `arr` таким образом, чтобы по строкам шли магазины, а по столбцам – дни (1 строка = 1 магазин). Сохранить изменения. Проверить, что форма массива изменилась.

In [24]:
### YOUR CODE HERE ###
arr_t = arr.transpose()
print(arr_t)

[[100  65  80  45  82 115  46]
 [ 80  55  90  60  47 120  74]
 [ 70  20  75  70  56 113  23]
 [ 60  50  80  20  89 106  34]
 [120  60  60  40  92 107  19]]


### Задание 19

Давайте представим, что информация по продажам обновилась: оказалось, что пятый магазин в воскресенье продал не 19 порций мороженого, а 25, и второй магазин продал во вторник не 55 порций, а 65. Изменить массив `arr` в соответствии с этой информацией.

In [25]:
### YOUR CODE HERE ###
arr_t[4][6] = 25
arr_t[1][1] = 65

print(arr_t)

[[100  65  80  45  82 115  46]
 [ 80  65  90  60  47 120  74]
 [ 70  20  75  70  56 113  23]
 [ 60  50  80  20  89 106  34]
 [120  60  60  40  92 107  25]]


### Задание 20

Посчитать суммарный объём продаж мороженого по всем магазинам.

In [26]:
### YOUR CODE HERE ###
print(np.sum(arr_t))

2439


### Задание 21
Создать список `turnout` (*list*, не массив), содержащий следующие значения явки на избирательные участки в процентах:

23.56, 45.78, 34.92, 57.34, 56.55, 67.23.

Создать, используя генераторы списков и встроенные, не из `NumPy`, функции для округления, новый список `turnout_r`, который состоит из округлённых до первого знака после запятой значений явки из `turnout`.

In [27]:
### YOUR CODE HERE ###
turnout = 	[23.56, 45.78, 34.92, 57.34, 56.55, 67.23]

for i in range(len(turnout)):
	print(round(turnout[i],1))


23.6
45.8
34.9
57.3
56.5
67.2


### Задание 22
Выполнить те же операции, что и в предыдущей задаче, но с использованием массивов и функций `NumPy`. Другими словами, создать массив `turnout` и на его основе создать массив `turnout_r` с округлёнными до первого знака значениями явки.

In [28]:
### YOUR CODE HERE ###
turnout2 = np.array([23.56, 45.78, 34.92, 57.34, 56.55, 67.23])
turnout_r = np.round(turnout2, 1)
print(turnout2)
print(turnout_r)


[23.56 45.78 34.92 57.34 56.55 67.23]
[23.6 45.8 34.9 57.3 56.6 67.2]
