Ботов Анатолий КИ22-08Б

Импортируйте библиотеку **numpy** с псевдонимом **np**

In [6]:
import numpy as np

1. Создайте трехмерный массив arr, заполненный 0 (массив должен содержать три слоя, две строки и четыре столбца) и определите его количество измерений.

In [7]:
# здесь должен быть ваш код
arr = np.zeros((3,2,4))
dimensions = arr.ndim
print(arr)
print("Количество измерений:", dimensions)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
Количество измерений: 3


2. Создайте матрицу 3x4 заполненную единицами и определите её размеры.

In [8]:
# здесь должен быть ваш код
matrix = np.ones((3,4))
matrix_shape = matrix.shape

print("Матрица:")
print(matrix)
print("Размеры матрицы:", matrix_shape)

Матрица:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Размеры матрицы: (3, 4)


3.  Создайте массив original_array с элементами(1, 2, 3).
    Создайте массив tiled_array следующим образом: повторите массив original_array 4 раза вдоль оси 0(строки) и дополнительно, каждую строку массива увеличьте по размеру в два раза с те же элементами (вдоль оси 1(столбцы)).

In [9]:
# здесь должен быть ваш код
original_array = ([1, 2, 3])
print("Исходный массив:")
print(original_array)

tiled_array = np.tile(original_array, (4, 2))
print("Массив с повторенными элементами:")
print(tiled_array)

# Исходный массив:
# [1 2 3]
# Массив с повторенными элементами:
# [[1 2 3 1 2 3]
#  [1 2 3 1 2 3]
#  [1 2 3 1 2 3]
#  [1 2 3 1 2 3]]

Исходный массив:
[1, 2, 3]
Массив с повторенными элементами:
[[1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]]


4. Предположим, у вас есть два датасета с данными о температуре и влажности.
Каждый датасет представлен в виде двумерного массива, где строки представляют дни, а столбцы представляют конкретные моменты времени в течение дня.
Тип данных - float.

Создайте два датасета размерностью 7 * 5 и заполните их случайными числами с плавающей точкой, вид распределения - равномерное.  
Температура должна иметь значения в интервале [-10,10] Влажность - значения в интервале [0,1]  

Преобразуйте датасет температуры на к целочисленному типу с соблюдением правил округления.
Выведите исходное и полученное значение датасета.

In [10]:
# здесь должен быть ваш код для начального заполнения массива
temp_data = np.random.uniform(-10,10, size =(7,5))
humid_data = np.random.uniform(0,1, size =(7,5))
np.set_printoptions(suppress=True)
print("Температура (float):")
print(temp_data)
print("Влажность (float):")
print(humid_data)

# здесь должен быть ваш код для преобразования типа данных
temp_data = np.round(temp_data).astype(int)
print("Температура (int):")
print(temp_data)

Температура (float):
[[-0.08388001  2.97693754 -9.72480625 -3.27099159 -5.13873684]
 [ 0.02771968  5.78304576 -7.94229082  5.01257991 -8.56410224]
 [ 8.35644185  2.39324461 -1.82119372  6.96647677  0.61218166]
 [-9.96587272  0.56374306 -6.24358733  3.81379382 -3.113869  ]
 [-5.90457561 -1.34390017 -0.10765096 -1.15727989 -7.32308382]
 [ 1.7437874  -8.62206126  1.54603796 -6.35476055  5.83750645]
 [-8.39234797  3.97168534  8.56339459 -6.44913642 -6.35947775]]
Влажность (float):
[[0.982888   0.27248795 0.96893832 0.28459187 0.52313129]
 [0.09972322 0.63360649 0.32689515 0.18955621 0.2928139 ]
 [0.46713072 0.72673718 0.24761913 0.49882989 0.62741687]
 [0.57543608 0.45239879 0.09213591 0.72366169 0.80083966]
 [0.85508655 0.64650908 0.49945104 0.88702523 0.6679528 ]
 [0.55088417 0.64331246 0.20800078 0.5558221  0.64918558]
 [0.23446266 0.31242263 0.99399618 0.34324617 0.66211094]]
Температура (int):
[[  0   3 -10  -3  -5]
 [  0   6  -8   5  -9]
 [  8   2  -2   7   1]
 [-10   1  -6   4  -3]


5. Любым способом создайте трехмерный массив tensor целых чисел (3, 3, 3) - (слой, строка, столбец), заполненный последовательными числами от 0 до N.
Выберите все элементы второй строки для каждого слоя.

In [11]:
# здесь должен быть ваш код

arr = np.arange(27)
tensor = arr.reshape((3,3,3))
print(tensor)

# здесь должен быть ваш код

result = tensor[:,1]
print(f'Элементы второй строки:\n{result}')

# [[[ 0  1  2]
#   [ 3  4  5]
#   [ 6  7  8]]

#  [[ 9 10 11]
#   [12 13 14]
#   [15 16 17]]

#  [[18 19 20]
#   [21 22 23]
#   [24 25 26]]]
# Элементы второй строки:
# [[ 3  4  5]
#  [12 13 14]
#  [21 22 23]]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Элементы второй строки:
[[ 3  4  5]
 [12 13 14]
 [21 22 23]]


6. Создайте двумерный массив dataset (5, 5) чисел с плавающей точкой.  
Заполненните его случайными числами с нормальным распределением и мат.ожиданием 1.  
Посчитайте среднее значение по столбцам, среднее и медиану всего массива.  
Выведите на экран исходный массив и полученные результаты.

In [12]:
# здесь должен быть ваш код

dataset = np.random.normal(loc=1, scale=1, size=(5, 5))
print(dataset)
print(np.mean(dataset,axis=0))
print(np.mean(dataset),np.median(dataset) )

# print(array_2D[:,1])

# [[ 0.44478058  0.98807546  0.19881689  1.04434615 -0.63199155]
#  [ 1.70859468 -0.08681621  1.44626959  1.26487098  0.941131  ]
#  [-0.37135468  0.3656662  -1.32059697 -0.13918286  0.06501245]
#  [ 0.6321983   0.89001849 -0.36688115  0.08899795 -0.84583768]
#  [ 0.05220295  0.17345485 -1.1245083  -0.51078062  1.33326499]
#  [ 0.02133517 -0.76891222  0.42070643 -1.15079269 -0.6385807 ]
#  [-0.12008171  1.04741544  0.62029783  1.16133434 -1.10282601]]
# [ 0.33823933  0.37270029 -0.0179851   0.25125618 -0.12568964]
# 0.16370421082065825 0.08899794516356198

[[ 0.87515829  0.99670559 -0.04609135  1.33629369  0.60310063]
 [-0.23935432  1.08725865  1.34190703  1.4360641   0.86296681]
 [ 0.29724682  1.91367906  2.70311482 -0.40142732  1.10682856]
 [ 1.43418916  0.0683021   0.81737246  2.00903661  3.57081455]
 [ 1.18777333  0.78657562  1.15593937  2.52417851  0.58668946]]
[0.71100266 0.97050421 1.19444847 1.38082912 1.34608   ]
1.1205728896692966 1.0872586540365259


7. Создайте массив result следующим образом: выберите из массива dataset все строки, в которых есть хотя бы одно число больше 1.

In [13]:
# здесь должен быть ваш код
result = dataset[np.any(dataset > 1, axis=1)]
print(result)

[[ 0.87515829  0.99670559 -0.04609135  1.33629369  0.60310063]
 [-0.23935432  1.08725865  1.34190703  1.4360641   0.86296681]
 [ 0.29724682  1.91367906  2.70311482 -0.40142732  1.10682856]
 [ 1.43418916  0.0683021   0.81737246  2.00903661  3.57081455]
 [ 1.18777333  0.78657562  1.15593937  2.52417851  0.58668946]]


8. Замените в массиве dataset все отрицательные числа на 0 и выведите результат.

In [14]:
# здесь должен быть ваш код
condition = dataset < 0
dataset[condition] = 0

print(dataset)

[[0.87515829 0.99670559 0.         1.33629369 0.60310063]
 [0.         1.08725865 1.34190703 1.4360641  0.86296681]
 [0.29724682 1.91367906 2.70311482 0.         1.10682856]
 [1.43418916 0.0683021  0.81737246 2.00903661 3.57081455]
 [1.18777333 0.78657562 1.15593937 2.52417851 0.58668946]]


9. Предположим, что dataset, полученный после выполнения п. 8, - это набор данных о продажах товаров. Каждая строка представляет собой информацию о продажах по дням недели, а столбцы содержат информацию о доходе от продажи товара.
Есть ли хотя бы один товар с нулевыми продажами?
В какой день недели доход от продаж максимальный?

In [25]:
# здесь должен быть ваш код
zero_sale = np.any(dataset == 0)

# Результат проверки
if zero_sale:
    print("0+")
else:
    print("0-")
max_a_day = np.argmax(np.sum(dataset, axis=1))
print(max_a_day)


0+
3


10. Дан массив data, содержащий информацию о студентах: имя, возраст, пол, курс и средний балл.
    Создайте массив result, содержащий имена, средние баллы и другую информацию студентов, которые старше 20 лет, женского пола и учатся на третьем курсе. 

In [16]:
import numpy as np
data = np.array([
    ['Анна', 19, 'F', 1, 4.5],
    ['Борис', 21, 'M', 2, 3.7],
    ['Вера', 21, 'F', 3, 4.8],
    ['Глеб', 22, 'M', 4, 3.9],
    ['Дарья', 18, 'F', 1, 4.2],
    ['Егор', 23, 'M', 3, 4.1],
    ['Жанна', 21, 'F', 2, 4.6],
    ['Захар', 19, 'M', 1, 4.0]
])

# здесь должен быть ваш код
ages = data[:, 1].astype(int)
genders = data[:, 2]
courses = data[:, 3].astype(int)
condition = (ages > 20) & (genders == 'F') & (courses == 3)
result = data[condition]

print("Студенты старше 20 лет, женского пола и на третьем курсе:")
print(result)


# [['Вера' '21' 'F' '3' '4.8']]

Студенты старше 20 лет, женского пола и на третьем курсе:
[['Вера' '21' 'F' '3' '4.8']]


11. У вас есть массив, представляющий собой скорости движения транспортного средства в км/ч: speeds = np.array([60, 75, 90, 100, 80, 65]).
    Создайте массив travel_times, содержащий расчетное время в пути для каждой скорости при преодолении расстояния 150 км с учетом замедления движения на 20%. Когда будете считать время, округлите  результат вниз, возвращая только целую часть.

In [17]:
import numpy as np

speeds = np.array([60, 75, 90, 100, 80, 65])
distance = 150
slowdown_rate = 0.80

# здесь должен быть ваш код

speeds_slowed = speeds * slowdown_rate
travel_times = distance/speeds_slowed
print(speeds_slowed)

print("Время в пути для каждой скорости:", np.floor(travel_times).astype(int))

# Время в пути для каждой скорости: [3. 2. 2. 1. 2. 2.]


[48. 60. 72. 80. 64. 52.]
Время в пути для каждой скорости: [3 2 2 1 2 2]


12. Создайте 2 двумерных целочисленных массива classification1 и classification2, заполненных случайными занчениями на интервале [0,10].  
С использованием методов NumPy сформируйте массив result, где каждый элемент равен 1, если классификации (classification1 и classification2) совпадают, и 0 в противном случае.

In [18]:
# здесь должен быть ваш код
arr1 = np.random.randint(0,10, size= (5,5))
arr2 = np.random.randint(0,10, size= (5,5))
print('arr1\n',arr1,'\narr2\n',arr2)

result = (arr1 == arr2).astype(int)
print('result\n',result )

# [[1 0 0 0 0]
#  [0 0 0 0 0]
#  [0 0 0 0 0]
#  [0 1 0 0 0]
#  [0 0 0 0 1]]

arr1
 [[7 4 7 9 0]
 [8 7 3 3 2]
 [4 7 1 0 5]
 [8 2 1 3 6]
 [5 0 3 1 9]] 
arr2
 [[1 3 4 7 3]
 [9 6 9 0 5]
 [1 8 2 5 9]
 [9 1 3 7 6]
 [4 3 7 2 9]]
result
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]]


13. Используя циклы написать собственную реализацию умножения двух двумерных матриц A и B, засечь время выполнения и сравнить его с функцией умножения матриц NumPy:

In [19]:
import time

n = 350 # значение может изменяться
A = np.random.rand(n, n)
B = np.random.rand(n, n)
C = np.zeros((n, n))
C_custom = np.zeros((n, n))
# print(A)
# print(B)
# print(C)

# Умножение матриц с использованием циклов
start_time = time.time()
for i in range(n):
    for j in range(n):
        for k in range(n):
            C_custom[i, j] += A[i, k] * B[k, j]
custom_time = time.time() - start_time

# Измерение времени выполнения NumPy
start_time = time.time()
C_numpy = np.dot(A, B)
numpy_time = time.time() - start_time

# Вывод результатов
print(f"Время выполнения собственной реализации: {custom_time:.6f} секунд")
print(f"Время выполнения NumPy: {numpy_time:.6f} секунд")

# Проверка корректности результата
print("Результаты совпадают:", np.allclose(C_custom, C_numpy))

Время выполнения собственной реализации: 16.084356 секунд
Время выполнения NumPy: 0.001904 секунд
Результаты совпадают: True


In [20]:
print("Умножения матриц - библиотечная функция NumPy: ")

Умножения матриц - библиотечная функция NumPy: 


In [21]:
%%time
# здесь должен быть ваш код

CPU times: total: 0 ns
Wall time: 0 ns


In [22]:
C = np.zeros((n, n))
print("Умножения матриц - собственная релизация: ")

Умножения матриц - собственная релизация: 


In [23]:
%%time
# здесь должен быть ваш код

CPU times: total: 0 ns
Wall time: 0 ns
