## Переменные и типы данных в Python
Переменная — это простейшая именованная структура данных, в которой может быть сохранён промежуточный или конечный результат работы программы.  
В Python тип переменной не задается явно, как, например в С++. 
В Python используется динамическая типизация, т.е. определение типа переменной происходит автоматически, когда вы присваиваете значение переменной.  
Чтобы оперативно просмотреть значение переменной в режиме ноутбука, можно в последней строке ячейки указать имя переменной.  
Для вывода, в том числе форматированного, используется функция **print(<список переменных>**.  
Определить тип переменной можно с помощью функции **type(<имя переменной>)**.

### *Встроенные типы данных*  

**int**  
Целые положительные или отрицательные числа.  
*Примечание: Нет отдельного типа ‘long int’ (длинное целое). Целые числа по умолчанию могут быть произвольной длины.*

In [4]:
var = 12344283333333333333333333388888888888888888888888888888222222222222227678492390
print('Тип переменной var:',type(var))
var

Тип переменной var: <class 'int'>


12344283333333333333333333388888888888888888888888888888222222222222227678492390

In [5]:
integer = -1234
print('Тип переменной integer:', type(integer)," Значение переменной integer: ", integer)

Тип переменной integer: <class 'int'>  Значение переменной integer:  -1234


**float**  
Числа с плавающей точкой.  
*Примечание: Числа могут быть комплексные.  Примеры комплексных чисел:(-5+4j) и (2.3-4.6j)*  

In [7]:
real = 12.56002
compl = (5-4j)
print('Тип переменной real:', type(real)," Значение переменной real: ", real)
print('Тип переменной compl:', type(compl)," Значение переменной compl: ", compl)

Тип переменной real: <class 'float'>  Значение переменной real:  12.56002
Тип переменной compl: <class 'complex'>  Значение переменной compl:  (5-4j)


**bool**  
Булевые значения, тип данных, принимающий одно из двух значений True - истина False - ложь. 

In [9]:
boolean = False
print('Тип переменной boolean:', type(boolean)," Значение переменной boolean: ", boolean)

Тип переменной boolean: <class 'bool'>  Значение переменной boolean:  False


**str**  
Строки символов (неизменяемый тип)

In [11]:
string = "Hello, World!"
print('Тип переменной string:', type(string)," Значение переменной string: ", string)
print("Вторая буква строки: ", string[1]) # нумерация начинается с 0!

Тип переменной string: <class 'str'>  Значение переменной string:  Hello, World!
Вторая буква строки:  e


**tup**  
Кортеж (Tuple), упорядоченная последовательность элементов (неизменяемый тип) 

In [13]:
tulpe = ('hostname', 1234, -0.45, -32)
print('Тип переменной tulpe:', type(tulpe)," Значение переменной tulpe: ", tulpe)
print("Третий элемент кортежа: ", tulpe[2]) # нумерация начинается с 0!

Тип переменной tulpe: <class 'tuple'>  Значение переменной tulpe:  ('hostname', 1234, -0.45, -32)
Третий элемент кортежа:  -0.45


**list**  
Cписок - упорядоченная последовательность элементов (изменяемый тип)

In [15]:
my_list=["Natalia","Krasnoyarsk",58,True,2]
print('Тип переменной my_list:', type(my_list))
print(my_list)

Тип переменной my_list: <class 'list'>
['Natalia', 'Krasnoyarsk', 58, True, 2]


In [16]:
my_list[1]='Moskva'
print(my_list)

['Natalia', 'Moskva', 58, True, 2]


**set**  
Множество - Неупорядоченная последовательность элементов (изменяемый тип)  

In [18]:
my_set={"Natalia","Krasnoyarsk",57,True,2}
print('Тип переменной my_set:', type(my_set)) 
print(my_set) #Порядок вывода элементов множества произвольный!
my_set[1]='Moskva' #В этой строке ошибка! Множество - Неупорядоченная последовательность элементов!
print(my_set) #Порядок вывода элементов множества произвольный!

Тип переменной my_set: <class 'set'>
{True, 2, 'Natalia', 57, 'Krasnoyarsk'}


TypeError: 'set' object does not support item assignment

In [50]:
my_set={"Natalia","Krasnoyarsk",57,True,2}
print(my_set) 
my_set.discard('Krasnoyarsk') #метод удаления элемента множества
print(my_set)
my_set.add('Moskva') #метод добавления элемента множества
print(my_set)

{True, 2, 'Natalia', 57, 'Krasnoyarsk'}
{True, 2, 'Natalia', 57}
{True, 2, 'Natalia', 'Moskva', 57}


**dict**  
Словарь - последовательность пар элементов содержащих ключ-значение (key-value) (изменяемый тип)  
Пример: {«Language»: «Python», «Version»: «3.8»}  

In [52]:
my_dict={"Name":"Natalia","City":"Krasnoyarsk","Age":57,"Married":True,"Children":2}
print('Тип переменной my_dict:', type(my_dict))
print(my_dict)
print(my_dict["Name"])
my_dict["City"]="Moskva"
print(my_dict)

Тип переменной my_dict: <class 'dict'>
{'Name': 'Natalia', 'City': 'Krasnoyarsk', 'Age': 57, 'Married': True, 'Children': 2}
Natalia
{'Name': 'Natalia', 'City': 'Moskva', 'Age': 57, 'Married': True, 'Children': 2}


Тип переменной может меняться!

In [54]:
var = 12344283333333333333333333388888888888888888888888888888222222222222227678492390
print('Тип переменной var:',type(var))
var = "String"
print('Тип переменной var:',type(var))

Тип переменной var: <class 'int'>
Тип переменной var: <class 'str'>


### Обратите внимание, что типа данных "массив" во встроенных типах данных Python нет!

Язык Python имеет лаконичный синтаксис и хорошо представленную документацию.  
[Документация Python](https://www.python.org/doc/)  

# Библиотеки Python  
Одним из преимуществ языка Python является большое количество библиотек для решения задач в самых различных областях.
В рамках нашего курса мы ознакомимся с наиболее популярными библиотеками в области работы с данными и искусственного интеллекта. 

## Библиотека NumPy
NumPy (сокращенно от Numerical Python) — библиотека с открытым исходным кодом для языка программирования Python.  
Библиотека NumPy предоставляет реализации вычислительных алгоритмов (в виде функций и операторов), оптимизированные для работы с многомерными массивами.  
Возможности:  
- поддержка многомерных массивов (включая матрицы);  
- поддержка высокоуровневых математических функций, предназначенных для работы с многомерными массивами.  

NumPy обеспечивает доступ к широкому спектру продвинутых математических функций, включая операции линейной алгебры, преобразования Фурье и генерацию случайных чисел.     
[Документация NumPy](https://numpy.org/doc/stable/reference/index.html)  

Нужно иметь в виду, что математические алгоритмы, реализованные на интерпретируемых языках, в том числе на Python, часто работают гораздо медленнее тех же алгоритмов, реализованных на компилируемых языках.  

### Импорт библиотеки и назначение псевдонима  
В языке программирования Python подключение пакетов, библиотек и модулей осуществляется с помощью функции import.   
При подключении пакета для для удобства работы и сокращения объема кода можно указать короткий псевдоним, по которому будет выполняться обращение к компонентам и функциям пакета:  
**import <имя библиотеки> as <псевдоним>** .   

In [2]:
import numpy as np

### Примитивные типы данных NumPy
NumPy поддерживает гораздо большее разнообразие числовых типов, чем Python. Поддерживаемые примитивные типы тесно связаны с типами в C.  
Наиболее часто используемые примитивные типы NumPy (более подробное и полное описание типов см. в документации):  
Numpy type    | C type| Примечание
--------------|------------------|----------
numpy.bool_	  | bool  
numpy.byte    | signed char  
numpy.ubyte	  | unsigned char  
numpy.short	  | short  
numpy.ushort  | unsigned short  
numpy.intc	  | int  
numpy.uintc	  | unsigned int  
numpy.int_	  | long  
numpy.uint	  | unsigned long  
numpy.longlong|	long long  
numpy.single  | float	|Platform-defined single precision float: typically sign bit, 8 bits exponent, 23 bits mantissa
numpy.single  | double	|Platform-defined double precision float: typically sign bit, 11 bits exponent, 52 bits mantissa

### Массивы в NumPy

**Создание пустого одномерного массива:** 
*Примечание: одномерные массивы NumPy называют векторами, и работа с ними имеет ряд особенностей.*

In [63]:
array_free = np.array([]) # обратите внимание на тип данных по умолчанию!
array_free

array([], dtype=float64)

**Создание одномерного массива (вектора) перечислением:**

In [3]:
array_1D = np.array([1., 0., 2., 3., 5., -1.])
array_1D

array([ 1.,  0.,  2.,  3.,  5., -1.])

In [4]:
a = np.array([2, 3, 6])
b = np.array([[4], [5], [1]]) # попробуйте понять, чем отличаются описания этих двух массивов до их вывода

print("a",a)
print("b",b)

In [67]:
print(a,'\n')
print(b)

[2 3 6] 

[[4]
 [5]
 [1]]


**Тип данных можно явно задать при создании массива:**

In [69]:
array_int32 = np.array([1],dtype = np.single)
print(array_int32.dtype, "- тип данных")
print(array_int32, "- значение переменных массива")

float32 - тип данных
[1.] - значение переменных массива


**Просмотр типа данных элементов массива:**

In [71]:
print(type(array_1D)) # Обратите внимание! Тип переменной array_1D и тип элементов массива array_1D - не одно и то же!
print(array_1D.dtype)

<class 'numpy.ndarray'>
float64


**Создание двумерного массива перечислением:**

In [73]:
array_2D = np.array([[1, 0, 2], [3, 4, 5], [6, 8, 7], [12, 22, 9]])
print(array_2D) # Какой тип будет у элементов этого массива? Попробуйте определить самостоятельно

[[ 1  0  2]
 [ 3  4  5]
 [ 6  8  7]
 [12 22  9]]


In [74]:
print(array_2D.dtype)

int32


**Вывод размерности массива:**

In [76]:
print(array_1D.shape, "- количество элементов одномерного массива")
print(array_2D.shape, "- количество строк и столбцов двумерного массива")

print(array_1D.size, "- количество элементов одномерного массива")
print(array_2D.size, "- количество элементов двумерно массива")

(6,) - количество элементов одномерного массива
(4, 3) - количество строк и столбцов двумерного массива
6 - количество элементов одномерного массива
12 - количество элементов двумерно массива


**Варианты автоматического заполнения массивов:**

In [78]:
np.ones((2, 2)) # заполнение единицами

array([[1., 1.],
       [1., 1.]])

In [79]:
np.zeros((2, 3))  # заполнение нулями

array([[0., 0., 0.],
       [0., 0., 0.]])

In [80]:
np.eye(4)  # заполнение диагональной единичной матрицей

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [81]:
np.random.random((2, 4))  # заполнение случайными числами

array([[0.15635623, 0.30108463, 0.3133626 , 0.34403678],
       [0.92087317, 0.46107193, 0.6824049 , 0.76340329]])

In [82]:
np.full((2, 2), 5)  # заполнение константой

array([[5, 5],
       [5, 5]])

In [83]:
array_1D = np.arange(15)  # заполнение последовательностью значений

**Обращение к элементу массива по его индексу:**  
*(индексация начинается с нуля)*

In [85]:
print(array_1D)
array_1D[1]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


1

In [86]:
print(array_2D)
array_2D[1, 2]

[[ 1  0  2]
 [ 3  4  5]
 [ 6  8  7]
 [12 22  9]]


5

In [87]:
print(array_2D[1])

[3 4 5]


In [88]:
print(array_2D[:,1])

[ 0  4  8 22]


In [89]:
print(array_2D[:, :])
array_2D[:2, :3]

[[ 1  0  2]
 [ 3  4  5]
 [ 6  8  7]
 [12 22  9]]


array([[1, 0, 2],
       [3, 4, 5]])

In [90]:
n = np.max(array_2D) # поиск максимального элемента массива
print(n)

22


In [91]:
n = np.argmax(array_1D) # индекс максимального элемента массива
print(array_1D)
print("Индекс максимального элемента массива: ", n, " Значение максимального элемента массива: ",array_1D[n])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Индекс максимального элемента массива:  14  Значение максимального элемента массива:  14


**Просмотр элементов массива, удовлетворяющих условию:**

In [93]:
array_2D > 5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [94]:
array_2D[array_2D > 5]

array([ 6,  8,  7, 12, 22,  9])

**Преобразование массива в вектор (одномерный массив):**

In [96]:
# функция flatten преобразует массив в одномерный
print(array_2D,"\n")
print(array_2D.flatten(),"\n") # Функция не изменяет исходный массив!
print(array_2D)

[[ 1  0  2]
 [ 3  4  5]
 [ 6  8  7]
 [12 22  9]] 

[ 1  0  2  3  4  5  6  8  7 12 22  9] 

[[ 1  0  2]
 [ 3  4  5]
 [ 6  8  7]
 [12 22  9]]


**Изменение размерности / размера массива по индексам:**  
*Примечание: часто под размерностью массива имеют в виду его размер по индексам, например "размерность массива 3 на 5 элементов".  
Но строго говоря, размерность массива - это число индексов, которые определяют положение элемента в массиве, например, двумерный массив - массив с размерностью 2, элемент определяется по двум индексам: номер строки и столбца.  
Приведенные ниже функции изменяют размер массива по индексам, т.е. форму массива (shape), а не его размерность.  
Хотя с их использованием можно изменить и размерность массива :) .*

In [98]:
print(array_2D)
array_2D.reshape(6,2) # Функция не изменяет исходный массив!

[[ 1  0  2]
 [ 3  4  5]
 [ 6  8  7]
 [12 22  9]]


array([[ 1,  0],
       [ 2,  3],
       [ 4,  5],
       [ 6,  8],
       [ 7, 12],
       [22,  9]])

In [99]:
# Метод resize() изменяет размерность массива и перезаписывает его
print(array_2D)
array_2D.resize(2, 6)
array_2D

[[ 1  0  2]
 [ 3  4  5]
 [ 6  8  7]
 [12 22  9]]


array([[ 1,  0,  2,  3,  4,  5],
       [ 6,  8,  7, 12, 22,  9]])

**Транспонирование массивов**

In [101]:
print(array_2D)
np.transpose(array_2D) # Функция не изменяет исходный массив!

[[ 1  0  2  3  4  5]
 [ 6  8  7 12 22  9]]


array([[ 1,  6],
       [ 0,  8],
       [ 2,  7],
       [ 3, 12],
       [ 4, 22],
       [ 5,  9]])

**Арифметические действия с массивами (поэлементные):**

In [103]:
a = np.array([[1, 2] , [3, 4]])
b = np.array([[2, 3] , [5, 6]])
print(a, '\n')
print(b)

[[1 2]
 [3 4]] 

[[2 3]
 [5 6]]


In [104]:
# поэлементное сложение
print(a + b, '\n')
print(np.add(a, b))

[[ 3  5]
 [ 8 10]] 

[[ 3  5]
 [ 8 10]]


In [105]:
# поэлементное вычитание
print(a - b, '\n')
print(np.subtract(a, b))

[[-1 -1]
 [-2 -2]] 

[[-1 -1]
 [-2 -2]]


In [106]:
# поэлементное деление
print(a / b, '\n')
print(np.divide(a, b))

[[0.5        0.66666667]
 [0.6        0.66666667]] 

[[0.5        0.66666667]
 [0.6        0.66666667]]


In [107]:
# ПОЭЛЕМЕНТНОЕ умножение массивов
print(a * b, '\n')
print(np.multiply(a, b))

[[ 2  6]
 [15 24]] 

[[ 2  6]
 [15 24]]


**Скалярное произведение массивов:**

In [109]:
print(a * 3)

[[ 3  6]
 [ 9 12]]


**Матричные операции над массивами**  
Плохая новость :) : для того, чтобы понять разницу между поэлементным и матричным умножением массивов, нужно вспомнить линейную алгебру!

In [111]:
print(a, '\n')
print(b, '\n')
# МАТРИЧНОЕ умножение массивов
print(np.dot(a, b), '\n') # функция библиотеки NumPy
print(a @ b) # оператор, определенный в библиотеке NumPy; предпочтительно использовать 

[[1 2]
 [3 4]] 

[[2 3]
 [5 6]] 

[[12 15]
 [26 33]] 

[[12 15]
 [26 33]]


**Вспоминаем особенности выполнения матричного умножения**

In [113]:
c = np.array([[1, 0, 2], [3, 4, 5], [6, 8, 7], [12, 22, 9]])
d = np.array([[3, 4, 5, 6], [8, 7, 6, 5], [12, 22, 9, 0]])
print(c,'\n')
print(d)

[[ 1  0  2]
 [ 3  4  5]
 [ 6  8  7]
 [12 22  9]] 

[[ 3  4  5  6]
 [ 8  7  6  5]
 [12 22  9  0]]


In [114]:
# попробуйте догадаться, что произойдет после запуска этого кода
print(np.dot(c,d),'\n')
print(c @ d,'\n')
print(c*d)

[[ 27  48  23   6]
 [101 150  84  38]
 [166 234 141  76]
 [320 400 273 182]] 

[[ 27  48  23   6]
 [101 150  84  38]
 [166 234 141  76]
 [320 400 273 182]] 



ValueError: operands could not be broadcast together with shapes (4,3) (3,4) 

In [115]:
d = np.transpose(d)
d

array([[ 3,  8, 12],
       [ 4,  7, 22],
       [ 5,  6,  9],
       [ 6,  5,  0]])

In [116]:
# попробуйте догадаться, что произойдет после запуска этого кода
print(c*d)
print(np.dot(c,d))

[[  3   0  24]
 [ 12  28 110]
 [ 30  48  63]
 [ 72 110   0]]


ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

**Однако с одномерными массивами - векторами - ситуация иная**

In [130]:
x = np.array([1, 3, 5, 6])
y = np.array([2, 4, 6, 7])

In [131]:
print(x)
print(y,'\n')
print(x * y)
print(np.dot(x, y))

[1 3 5 6]
[2 4 6 7] 

[ 2 12 30 42]
86


In [132]:
c = np.array([[2], [4], [6], [7]])
print(x,'\n')
print(c,'\n')
print(np.dot(x, c))

[1 3 5 6] 

[[2]
 [4]
 [6]
 [7]] 

[86]


### Другие операции с массивами и их элементами
**Суммирование элементов массива:**

In [134]:
a = np.array([1, 2, 3])
np.sum(a)

6

In [135]:
a = a * 2.0 # изменение типа элементов массива на float
print(a)
np.sum(a, dtype = np.int64) # суммирование элементов массива и приведение к типу int

[2. 4. 6.]


12

In [136]:
# сумма элементов по столбцам
a = np.array([[4, 5, 6], [2, 3, 4]])
np.sum(a, axis = 0)

array([ 6,  8, 10])

In [137]:
# сумма элементов по строкам
np.sum(a, axis = 1)

array([15,  9])

**Объединение массивов:**

In [139]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [140]:
print(np.stack((a, b)))
print()
print(np.stack((a, b), axis = 1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


**Разделение массивов:**

In [142]:
a = np.arange(5)
c = np.array_split(a, 3)
print(c[0])
print(c[1])
print(c[2])

[0 1]
[2 3]
[4]


**Другие действия с массивами:**

In [144]:
# подсчет количества вхождений каждого элемента массива
a = np.array([0, 1, 2, 2, 1, 1, 3, 3, 3, 4]) 
np.bincount(a)

array([1, 3, 2, 3, 1], dtype=int64)

In [145]:
a = np.random.randint(1, 10, 10) 
print(a)
np.argpartition(a, kth = 3) # сортирует kth-ый элемент массива, 
                            # значения меньше kth-ого элемента будут расположены слева от него, 
                            # а больше - справа в произвольном порядке. Функция возвращает ИНДЕКСЫ элементов.

[9 4 4 3 3 6 9 7 5 7]


array([4, 3, 1, 2, 8, 5, 9, 7, 6, 0], dtype=int64)

In [146]:
# удаление строк или столбцов матрицы
np.arange(4, 6, 1)
a = np.array([np.arange(3), np.arange(3,6)])
print(a, "\n")
print(np.delete(a, 1, axis = 1)) # удаление второго столбца
print()
print(np.delete(a, 0, axis = 0)) # удаление первой строки

[[0 1 2]
 [3 4 5]] 

[[0 2]
 [3 5]]

[[3 4 5]]


## ДАЛЕЕ ПЕРЕХОДИМ К ВЫПОЛНЕНИЮ ЗАДАНИЯ 1.1