ЗДЕСЬ НУЖНО УКАЗАТЬ ГРУППУ, ФАМИЛИЮ И ИМЯ СТУДЕНТА

Импортируйте библиотеку **numpy** с псевдонимом **np**

In [2]:
# здесь должен быть ваш код

1. Создайте трехмерный массив arr, заполненный 0 (массив должен содержать три слоя, две строки и четыре столбца) и определите его количество измерений.

In [4]:
# здесь должен быть ваш код

print(arr)
print("Количество измерений:", dimensions)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
Количество измерений: 3


2. Создайте матрицу 3x4 заполненную единицами и определите её размеры.

In [6]:
# здесь должен быть ваш код

print("Матрица:")
print(matrix)
print("Размеры матрицы:", matrix_shape)

Матрица:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Размеры матрицы: (3, 4)


3.  Создайте массив original_array с элементами(1, 2, 3).
    Создайте массив tiled_array следующим образом: повторите массив original_array 4 раза вдоль оси 0(строки) и дополнительно, каждую строку массива увеличьте по размеру в два раза с те же элементами (вдоль оси 1(столбцы)).

In [8]:
# здесь должен быть ваш код

print("Исходный массив:")
print(original_array)

print("Массив с повторенными элементами:")
print(tiled_array)

Исходный массив:
[1 2 3]
Массив с повторенными элементами:
[[1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]]


4. Предположим, у вас есть два датасета с данными о температуре и влажности.
Каждый датасет представлен в виде двумерного массива, где строки представляют дни, а столбцы представляют конкретные моменты времени в течение дня.
Тип данных - float.

Создайте два датасета размерностью 7 * 5 и заполните их случайными числами с плавающей точкой, вид распределения - равномерное.  
Температура должна иметь значения в интервале [-10,10] Влажность - значения в интервале [0,1]  

Преобразуйте датасет температуры на к целочисленному типу с соблюдением правил округления.
Выведите исходное и полученное значение датасета.

In [10]:
# здесь должен быть ваш код для начального заполнения массива

print("Температура (float):")
print(temp_data)
print("Влажность (float):")
print(humid_data)

# здесь должен быть ваш код для преобразования типа данных

print("Температура (int):")
print(temp_data)

Температура (float):
[[ 3.28313417  1.41060146  0.52339236 -4.23916428  1.14564842]
 [-0.07362926  1.04741136  4.32240706  2.96251083 -2.93620708]
 [ 1.0866735  -2.0950439  -2.55373427 -3.01546759  4.94510537]
 [ 3.29603965  0.65670996 -0.78829377  2.42554168 -1.81933098]
 [ 2.13933014 -3.37765565 -4.71250567 -0.18291939 -2.29000811]
 [-1.49790453  1.10927076  3.50821405  0.58749     3.21799864]
 [ 2.50612282 -1.16413292 -4.62151379 -4.27596488 -0.50804783]]
Влажность (float):
[[0.01747722 0.39399505 0.20383821 0.94279226 0.13759194]
 [0.40753082 0.60918596 0.2007321  0.4296817  0.71308698]
 [0.90528029 0.0934367  0.67771902 0.12791844 0.95332508]
 [0.61876495 0.91199483 0.21751383 0.29293528 0.921164  ]
 [0.21401418 0.61121282 0.94256756 0.99448264 0.20991902]
 [0.6255441  0.25003799 0.18178375 0.52202002 0.08172789]
 [0.7087556  0.47049628 0.42129361 0.82190256 0.72289235]]
Новый тип данных temp_data: int32
Температура (int):
[[ 3  1  1 -4  1]
 [ 0  1  4  3 -3]
 [ 1 -2 -3 -3  5]
 [ 3

5. Любым способом создайте трехмерный массив tensor целых чисел (3, 3, 3) - (слой, строка, столбец), заполненный последовательными числами от 0 до N.
Выберите все элементы второй строки для каждого слоя.

In [12]:
# здесь должен быть ваш код
print(tensor)

# здесь должен быть ваш код
print(f'Элементы второй строки:\n{result}')

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Элементы второй строки:
[[ 3  4  5]
 [12 13 14]
 [21 22 23]]


6. Создайте двумерный массив dataset (5, 5) чисел с плавающей точкой.  
Заполненните его случайными числами с нормальным распределением и мат.ожиданием 1.  
Посчитайте среднее значение по столбцам, среднее и медиану всего массива.  
Выведите на экран исходный массив и полученные результаты.

In [131]:
# здесь должен быть ваш код


[[ 0.44478058  0.98807546  0.19881689  1.04434615 -0.63199155]
 [ 1.70859468 -0.08681621  1.44626959  1.26487098  0.941131  ]
 [-0.37135468  0.3656662  -1.32059697 -0.13918286  0.06501245]
 [ 0.6321983   0.89001849 -0.36688115  0.08899795 -0.84583768]
 [ 0.05220295  0.17345485 -1.1245083  -0.51078062  1.33326499]
 [ 0.02133517 -0.76891222  0.42070643 -1.15079269 -0.6385807 ]
 [-0.12008171  1.04741544  0.62029783  1.16133434 -1.10282601]]
[ 0.33823933  0.37270029 -0.0179851   0.25125618 -0.12568964]
0.16370421082065825 0.08899794516356198


7. Создайте массив result следующим образом: выберите из массива dataset все строки, в которых есть хотя бы одно число больше 1.

In [134]:
# здесь должен быть ваш код
print(result)

[[ 0.44478058  0.98807546  0.19881689  1.04434615 -0.63199155]
 [ 1.70859468 -0.08681621  1.44626959  1.26487098  0.941131  ]
 [ 0.05220295  0.17345485 -1.1245083  -0.51078062  1.33326499]
 [-0.12008171  1.04741544  0.62029783  1.16133434 -1.10282601]]


8. Замените в массиве dataset все отрицательные числа на 0 и выведите результат.

In [137]:
# здесь должен быть ваш код

print(dataset)

[[0.44478058 0.98807546 0.19881689 1.04434615 0.        ]
 [1.70859468 0.         1.44626959 1.26487098 0.941131  ]
 [0.         0.3656662  0.         0.         0.06501245]
 [0.6321983  0.89001849 0.         0.08899795 0.        ]
 [0.05220295 0.17345485 0.         0.         1.33326499]
 [0.02133517 0.         0.42070643 0.         0.        ]
 [0.         1.04741544 0.62029783 1.16133434 0.        ]]


9. Предположим, что dataset, полученный после выполнения п. 8, - это набор данных о продажах товаров. Каждая строка представляет собой информацию о продажах по дням недели, а столбцы содержат информацию о доходе от продажи товара.
Есть ли хотя бы один товар с нулевыми продажами?
В какой день недели доход от продаж максимальный?

In [159]:
# здесь должен быть ваш код


10. Дан массив data, содержащий информацию о студентах: имя, возраст, пол, курс и средний балл.
    Создайте массив result, содержащий имена, средние баллы и другую информацию студентов, которые старше 20 лет, женского пола и учатся на третьем курсе. 

In [22]:
import numpy as np
data = np.array([
    ['Анна', 19, 'F', 1, 4.5],
    ['Борис', 21, 'M', 2, 3.7],
    ['Вера', 21, 'F', 3, 4.8],
    ['Глеб', 22, 'M', 4, 3.9],
    ['Дарья', 18, 'F', 1, 4.2],
    ['Егор', 23, 'M', 3, 4.1],
    ['Жанна', 21, 'F', 2, 4.6],
    ['Захар', 19, 'M', 1, 4.0]
])

# здесь должен быть ваш код
print(result)

[['Вера' '21' 'F' '3' '4.8']]


11. У вас есть массив, представляющий собой скорости движения транспортного средства в км/ч: speeds = np.array([60, 75, 90, 100, 80, 65]).
    Создайте массив travel_times, содержащий расчетное время в пути для каждой скорости при преодолении расстояния 150 км с учетом замедления движения на 20%. Когда будете считать время, округлите  результат вниз, возвращая только целую часть.

In [24]:
import numpy as np

speeds = np.array([60, 75, 90, 100, 80, 65])
distance = 150
slowdown_rate = 0.20

# здесь должен быть ваш код

print("Время в пути для каждой скорости:", travel_times)

Время в пути для каждой скорости: [3. 2. 2. 1. 2. 2.]


12. Создайте 2 двумерных целочисленных массива classification1 и classification2, заполненных случайными занчениями на интервале [0,10].  
С использованием методов NumPy сформируйте массив result, где каждый элемент равен 1, если классификации (classification1 и classification2) совпадают, и 0 в противном случае.

In [26]:
# здесь должен быть ваш код

print(result)

[[1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 1]]


13. Используя циклы написать собственную реализацию умножения двух двумерных матриц A и B, засечь время выполнения и сравнить его с функцией умножения матриц NumPy:

In [9]:
import numpy as np
n = 500 # значение может изменяться
A = np.random.rand(n, n)
B = np.random.rand(n, n)
C = np.zeros((n, n))

In [21]:
print("Умножения матриц - библиотечная функция NumPy: ")

Умножения матриц - библиотечная функция NumPy: 


In [23]:
%%time
# здесь должен быть ваш код

CPU times: total: 0 ns
Wall time: 2 ms


In [25]:
C = np.zeros((n, n))
print("Умножения матриц - собственная релизация: ")

Умножения матриц - собственная релизация: 


In [29]:
%%time
# здесь должен быть ваш код

CPU times: total: 0 ns
Wall time: 0 ns
