Ботов Анатолий КИ22-08Б

Импортируйте библиотеку **numpy** с псевдонимом **np**

In [2]:
import numpy as np

1. Создайте трехмерный массив arr, заполненный 0 (массив должен содержать три слоя, две строки и четыре столбца) и определите его количество измерений.

In [5]:
# здесь должен быть ваш код
arr = np.zeros((3,2,4))
dimensions = arr.ndim
print(arr)
print("Количество измерений:", dimensions)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
Количество измерений: 3


2. Создайте матрицу 3x4 заполненную единицами и определите её размеры.

In [7]:
# здесь должен быть ваш код
matrix = np.ones((3,4))
matrix_shape = matrix.shape

print("Матрица:")
print(matrix)
print("Размеры матрицы:", matrix_shape)

Матрица:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Размеры матрицы: (3, 4)


3.  Создайте массив original_array с элементами(1, 2, 3).
    Создайте массив tiled_array следующим образом: повторите массив original_array 4 раза вдоль оси 0(строки) и дополнительно, каждую строку массива увеличьте по размеру в два раза с те же элементами (вдоль оси 1(столбцы)).

In [39]:
# здесь должен быть ваш код
original_array = ([1, 2, 3])
print("Исходный массив:")
print(original_array)

tiled_array = np.tile(original_array, (4, 2))
print("Массив с повторенными элементами:")
print(tiled_array)

# Исходный массив:
# [1 2 3]
# Массив с повторенными элементами:
# [[1 2 3 1 2 3]
#  [1 2 3 1 2 3]
#  [1 2 3 1 2 3]
#  [1 2 3 1 2 3]]

Исходный массив:
[1, 2, 3]
Массив с повторенными элементами:
[[1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]]


4. Предположим, у вас есть два датасета с данными о температуре и влажности.
Каждый датасет представлен в виде двумерного массива, где строки представляют дни, а столбцы представляют конкретные моменты времени в течение дня.
Тип данных - float.

Создайте два датасета размерностью 7 * 5 и заполните их случайными числами с плавающей точкой, вид распределения - равномерное.  
Температура должна иметь значения в интервале [-10,10] Влажность - значения в интервале [0,1]  

Преобразуйте датасет температуры на к целочисленному типу с соблюдением правил округления.
Выведите исходное и полученное значение датасета.

In [220]:
# здесь должен быть ваш код для начального заполнения массива
temp_data = np.random.uniform(-10,10, size =(7,5))
humid_data = np.random.uniform(0,1, size =(7,5))
np.set_printoptions(suppress=True)
print("Температура (float):")
print(temp_data)
print("Влажность (float):")
print(humid_data)

# здесь должен быть ваш код для преобразования типа данных
temp_data = np.round(temp_data).astype(int)
print("Температура (int):")
print(temp_data)

Температура (float):
[[-4.77308606 -9.69959384  4.79286695 -9.45641735  9.23915823]
 [ 9.39321666 -8.08444272  2.48587368 -7.92574011 -4.95715174]
 [-1.81371622 -2.62256166  9.87391969  7.0968997   7.95486379]
 [-8.4742225   7.13944754  6.60816494 -3.26012376 -0.03010842]
 [ 5.43025947 -8.03713608 -5.73473903  5.13592234 -0.66184207]
 [-1.17390846  4.10831637 -7.21909662 -2.67882039  2.54438138]
 [-5.14773617 -4.17065811  5.06334229 -0.03921456 -3.38255124]]
Влажность (float):
[[0.7331656  0.0745213  0.86998671 0.04298936 0.16422463]
 [0.67767855 0.45000225 0.34493343 0.24515569 0.20945438]
 [0.4738326  0.56954422 0.37987011 0.81543723 0.64582115]
 [0.01781146 0.81765119 0.17090698 0.16103747 0.70314087]
 [0.9885036  0.76135189 0.96302566 0.14262955 0.56812753]
 [0.31117432 0.5715924  0.83524465 0.16311423 0.16215956]
 [0.57969454 0.62190805 0.51574804 0.75072899 0.17892599]]
Температура (int):
[[ -5 -10   5  -9   9]
 [  9  -8   2  -8  -5]
 [ -2  -3  10   7   8]
 [ -8   7   7  -3   0]


5. Любым способом создайте трехмерный массив tensor целых чисел (3, 3, 3) - (слой, строка, столбец), заполненный последовательными числами от 0 до N.
Выберите все элементы второй строки для каждого слоя.

In [245]:
# здесь должен быть ваш код

arr = np.arange(27)
tensor = arr.reshape((3,3,3))
print(tensor)

# здесь должен быть ваш код

result = tensor[:,1]
print(f'Элементы второй строки:\n{result}')

# [[[ 0  1  2]
#   [ 3  4  5]
#   [ 6  7  8]]

#  [[ 9 10 11]
#   [12 13 14]
#   [15 16 17]]

#  [[18 19 20]
#   [21 22 23]
#   [24 25 26]]]
# Элементы второй строки:
# [[ 3  4  5]
#  [12 13 14]
#  [21 22 23]]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Элементы второй строки:
[[ 3  4  5]
 [12 13 14]
 [21 22 23]]


6. Создайте двумерный массив dataset (5, 5) чисел с плавающей точкой.  
Заполненните его случайными числами с нормальным распределением и мат.ожиданием 1.  
Посчитайте среднее значение по столбцам, среднее и медиану всего массива.  
Выведите на экран исходный массив и полученные результаты.

In [254]:
# здесь должен быть ваш код

dataset = np.random.normal(loc=1, scale=1, size=(5, 5))
print(dataset)
print(np.mean(dataset,axis=0))
print(np.mean(dataset),np.median(dataset) )

# print(array_2D[:,1])

# [[ 0.44478058  0.98807546  0.19881689  1.04434615 -0.63199155]
#  [ 1.70859468 -0.08681621  1.44626959  1.26487098  0.941131  ]
#  [-0.37135468  0.3656662  -1.32059697 -0.13918286  0.06501245]
#  [ 0.6321983   0.89001849 -0.36688115  0.08899795 -0.84583768]
#  [ 0.05220295  0.17345485 -1.1245083  -0.51078062  1.33326499]
#  [ 0.02133517 -0.76891222  0.42070643 -1.15079269 -0.6385807 ]
#  [-0.12008171  1.04741544  0.62029783  1.16133434 -1.10282601]]
# [ 0.33823933  0.37270029 -0.0179851   0.25125618 -0.12568964]
# 0.16370421082065825 0.08899794516356198

[[-1.31674176 -0.20946308  1.46389483  0.70265345  2.09307054]
 [ 3.04025545  1.11505074  2.14033531  1.20405444  0.84898154]
 [ 2.32924932  0.88164119  1.22588723  1.08766536  0.14401684]
 [-0.22783357  2.94075768  3.19452043  2.88050428  1.69005535]
 [ 1.0169766  -0.27820678  3.05639057  0.51775441  0.71520397]]
[0.96838121 0.88995595 2.21620567 1.27852639 1.09826565]
1.290266974157259 1.1150507411955313


7. Создайте массив result следующим образом: выберите из массива dataset все строки, в которых есть хотя бы одно число больше 1.

In [258]:
# здесь должен быть ваш код
result = dataset[np.any(dataset > 1, axis=1)]
print(result)

[[-1.31674176 -0.20946308  1.46389483  0.70265345  2.09307054]
 [ 3.04025545  1.11505074  2.14033531  1.20405444  0.84898154]
 [ 2.32924932  0.88164119  1.22588723  1.08766536  0.14401684]
 [-0.22783357  2.94075768  3.19452043  2.88050428  1.69005535]
 [ 1.0169766  -0.27820678  3.05639057  0.51775441  0.71520397]]


8. Замените в массиве dataset все отрицательные числа на 0 и выведите результат.

In [262]:
# здесь должен быть ваш код
condition = dataset < 0
dataset[condition] = 0

print(dataset)

[[0.         0.         1.46389483 0.70265345 2.09307054]
 [3.04025545 1.11505074 2.14033531 1.20405444 0.84898154]
 [2.32924932 0.88164119 1.22588723 1.08766536 0.14401684]
 [0.         2.94075768 3.19452043 2.88050428 1.69005535]
 [1.0169766  0.         3.05639057 0.51775441 0.71520397]]


9. Предположим, что dataset, полученный после выполнения п. 8, - это набор данных о продажах товаров. Каждая строка представляет собой информацию о продажах по дням недели, а столбцы содержат информацию о доходе от продажи товара.
Есть ли хотя бы один товар с нулевыми продажами?
В какой день недели доход от продаж максимальный?

In [263]:
# здесь должен быть ваш код
print(dataset.max(axis=0)) ################## kod gavno here. todo


[3.04025545 2.94075768 3.19452043 2.88050428 2.09307054]


10. Дан массив data, содержащий информацию о студентах: имя, возраст, пол, курс и средний балл.
    Создайте массив result, содержащий имена, средние баллы и другую информацию студентов, которые старше 20 лет, женского пола и учатся на третьем курсе. 

In [266]:
import numpy as np
data = np.array([
    ['Анна', 19, 'F', 1, 4.5],
    ['Борис', 21, 'M', 2, 3.7],
    ['Вера', 21, 'F', 3, 4.8],
    ['Глеб', 22, 'M', 4, 3.9],
    ['Дарья', 18, 'F', 1, 4.2],
    ['Егор', 23, 'M', 3, 4.1],
    ['Жанна', 21, 'F', 2, 4.6],
    ['Захар', 19, 'M', 1, 4.0]
])

# здесь должен быть ваш код
ages = data[:, 1].astype(int)
genders = data[:, 2]
courses = data[:, 3].astype(int)
condition = (ages > 20) & (genders == 'F') & (courses == 3)
result = data[condition]

print("Студенты старше 20 лет, женского пола и на третьем курсе:")
print(result)


# [['Вера' '21' 'F' '3' '4.8']]

Студенты старше 20 лет, женского пола и на третьем курсе:
[['Вера' '21' 'F' '3' '4.8']]


11. У вас есть массив, представляющий собой скорости движения транспортного средства в км/ч: speeds = np.array([60, 75, 90, 100, 80, 65]).
    Создайте массив travel_times, содержащий расчетное время в пути для каждой скорости при преодолении расстояния 150 км с учетом замедления движения на 20%. Когда будете считать время, округлите  результат вниз, возвращая только целую часть.

In [278]:
import numpy as np

speeds = np.array([60, 75, 90, 100, 80, 65])
distance = 150
slowdown_rate = 0.80

# здесь должен быть ваш код

speeds_slowed = speeds * slowdown_rate
travel_times = distance/speeds_slowed
print(speeds_slowed)

print("Время в пути для каждой скорости:", np.floor(travel_times).astype(int))

# Время в пути для каждой скорости: [3. 2. 2. 1. 2. 2.]


[48. 60. 72. 80. 64. 52.]
Время в пути для каждой скорости: [3 2 2 1 2 2]


12. Создайте 2 двумерных целочисленных массива classification1 и classification2, заполненных случайными занчениями на интервале [0,10].  
С использованием методов NumPy сформируйте массив result, где каждый элемент равен 1, если классификации (classification1 и classification2) совпадают, и 0 в противном случае.

In [295]:
# здесь должен быть ваш код
arr1 = np.random.randint(0,10, size= (5,5))
arr2 = np.random.randint(0,10, size= (5,5))
print('arr1\n',arr1,'\narr2\n',arr2)

result = (arr1 == arr2).astype(int)
print('result\n',result )

# [[1 0 0 0 0]
#  [0 0 0 0 0]
#  [0 0 0 0 0]
#  [0 1 0 0 0]
#  [0 0 0 0 1]]

arr1
 [[0 0 9 4 9]
 [1 1 6 6 4]
 [4 3 7 0 2]
 [0 2 8 1 7]
 [8 6 4 1 4]] 
arr2
 [[4 3 5 3 3]
 [9 3 1 4 9]
 [6 9 2 0 0]
 [7 2 6 7 5]
 [3 7 4 3 2]]
result
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]


13. Используя циклы написать собственную реализацию умножения двух двумерных матриц A и B, засечь время выполнения и сравнить его с функцией умножения матриц NumPy:

In [316]:
import time

n = 50 # значение может изменяться
A = np.random.rand(n, n)
B = np.random.rand(n, n)
C = np.zeros((n, n))
C_custom = np.zeros((n, n))
# print(A)
# print(B)
# print(C)

# Умножение матриц с использованием циклов
start_time = time.time()
for i in range(n):
    for j in range(n):
        for k in range(n):
            C_custom[i, j] += A[i, k] * B[k, j]
custom_time = time.time() - start_time

# Измерение времени выполнения NumPy
start_time = time.time()
C_numpy = np.dot(A, B)
numpy_time = time.time() - start_time

# Вывод результатов
print(f"Время выполнения собственной реализации: {custom_time:.6f} секунд")
print(f"Время выполнения NumPy: {numpy_time:.6f} секунд")

# Проверка корректности результата
print("Результаты совпадают:", np.allclose(C_custom, C_numpy))

Время выполнения собственной реализации: 0.066821 секунд
Время выполнения NumPy: 0.000000 секунд
Результаты совпадают: True


In [21]:
print("Умножения матриц - библиотечная функция NumPy: ")

Умножения матриц - библиотечная функция NumPy: 


In [23]:
%%time
# здесь должен быть ваш код

CPU times: total: 0 ns
Wall time: 2 ms


In [25]:
C = np.zeros((n, n))
print("Умножения матриц - собственная релизация: ")

Умножения матриц - собственная релизация: 


In [29]:
%%time
# здесь должен быть ваш код

CPU times: total: 0 ns
Wall time: 0 ns
